// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLyQ-Hmvsn_pTggYKuttD4hNmMgVPJPY',
    appId: '1:291577605074:web:ad213f8d5dc47bb3f0f60b',
    messagingSenderId: '291577605074',
    projectId: 'praktikum-09-firebase',
    authDomain: 'praktikum-09-firebase.firebaseapp.com',
    storageBucket: 'praktikum-09-firebase.appspot.com',
    measurementId: 'G-PSMDSRDCZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepZCXgiJNeb7V5t8sPO4-6-Pj1f2KBrg',
    appId: '1:291577605074:android:a75dcac836b26148f0f60b',
    messagingSenderId: '291577605074',
    projectId: 'praktikum-09-firebase',
    storageBucket: 'praktikum-09-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG3zx-pPv4Exc8BSUXM-6LWzOFIg5ApRY',
    appId: '1:291577605074:ios:b38cea6c2c09005bf0f60b',
    messagingSenderId: '291577605074',
    projectId: 'praktikum-09-firebase',
    storageBucket: 'praktikum-09-firebase.appspot.com',
    iosBundleId: 'com.example.praktikum09Fazaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG3zx-pPv4Exc8BSUXM-6LWzOFIg5ApRY',
    appId: '1:291577605074:ios:b38cea6c2c09005bf0f60b',
    messagingSenderId: '291577605074',
    projectId: 'praktikum-09-firebase',
    storageBucket: 'praktikum-09-firebase.appspot.com',
    iosBundleId: 'com.example.praktikum09Fazaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLyQ-Hmvsn_pTggYKuttD4hNmMgVPJPY',
    appId: '1:291577605074:web:4951fbbf004f3d8af0f60b',
    messagingSenderId: '291577605074',
    projectId: 'praktikum-09-firebase',
    authDomain: 'praktikum-09-firebase.firebaseapp.com',
    storageBucket: 'praktikum-09-firebase.appspot.com',
    measurementId: 'G-CX6PD5J0S5',
  );
}
